spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    protocol: "smtp"
    host: "smtp.gmail.com"
    port: 587
    username: "ERP.Godzilla@gmail.com"
    password: "aqqxxdhlvfbgenvf"
    properties: 
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.http.server.reactive: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ERP.Godzilla@gmail.com
    password: aqqxxdhlvfbgenvf
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: "r2dbc:h2:mem:///testdb"
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ERP.Godzilla@gmail.com
    password: aqqxxdhlvfbgenvf
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"