spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.http.server.reactive: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: "r2dbc:h2:mem:///testdb"