name: Maven Build

on:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Test scenario tags'

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: godzilla
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        env:
          DB_HOST: "127.0.0.1"
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          docker ps -a
          pwd
          ls -al
          mvn -B clean package
